name: ci

on: push

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        env:
          DB_HOST: localhost
          DB_PORT: '3306'
          DB_DATABASE: ci
          DB_USERNAME: ci
          DB_PASSWORD: ci
        run: pnpm exec prisma generate

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck
